version: '3.3'

services:

#docker compose up -d
#loki
#graphana
   server:
        image: udbapp
        container_name: mainudbapp
        links:
            - redis-server
            - mongo_db
        environment:
            SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        ports:
            - "8082:8082"


   redis-server:
       hostname: redis
       image: redis
       ports:
         - "6379:6379"
         
   mongo_db:
      image: mongo
      container_name: mongoDB  
      ports:
        - 27017:27017

   zookeeper:
     image: confluentinc/cp-zookeeper:latest
     environment:
       ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000

   kafka:
     image: confluentinc/cp-kafka:latest
     depends_on:
       - zookeeper
     ports:
       - 9092:9092
     environment:
       KAFKA_BROKER_ID: 1
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

   loki:
     image: grafana/loki:latest
     command: [ "-config.file=/etc/loki/local-config.yaml" ]
     ports:
       - "3100:3100"

   grafana:
     image: grafana/grafana:latest
     volumes:
       - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
     environment:
       - GF_AUTH_ANONYMOUS_ENABLED=true
       - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
       - GF_AUTH_DISABLE_LOGIN_FORM=true
     ports:
       - "3000:3000"


