apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notesapp
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
      - name: notesapp
        image: notesapp
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: notesapp
spec:
  selector:
    app: notesapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
