apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notesapp
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
      - name: notesapp
        image: notesapp
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_KAFKA_BOOTSTRAPSERVERS
          value: kafka:29092
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /config/firebase-key.json
---
apiVersion: v1
kind: Service
metadata:
  name: notesapp
spec:
  selector:
    app: notesapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort
