apiVersion: apps/v1
kind: Deployment
metadata:
  name: udbapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udbapp
  template:
    metadata:
      labels:
        app: udbapp
    spec:
      containers:
      - name: udbapp
        image: udbapp
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: udbapp
spec:
  selector:
    app: udbapp
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
