services:
  usersapp:
    image: usersapp
    depends_on:
      - db
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userDB
      SPRING_DATASOURCE_USERNAME: teamtico
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - 8080:8080
    networks:
      - postgres
      - kafka
      - proxy

  db:
    image: postgres
    environment:
      POSTGRES_USER: teamtico
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka

  nginx:
    image: nginx-reverse-proxy
    ports:
      - "80:80"
    networks:
      - proxy

networks:
  postgres:
    driver: bridge
  kafka:
  proxy:

volumes:
  postgres:
  pgadmin:
#  redis_data: